name: Deploy Flet Web App
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Dist Package
        run: |
          mkdir -p ./dist
          
          cp index.html ./dist/
          cp flet.js ./dist/
          cp flet_main.py ./dist/
          cp boot.py ./dist/
          
          if [ -d "data" ]; then
            cp -r data ./dist/
          fi
          if [ -d "fonts" ]; then
            cp -r fonts ./dist/
          fi
          
          echo "=== 配信フォルダ（dist）の中身を確認 ==="
          ls -la ./dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
